//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteGenieDemoApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RouteGenieDemoApp.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Genie Demo App is built using ASP.net MVC with Microsoft.net Framework 4.8.
        /// </summary>
        public static string AppMessage {
            get {
                return ResourceManager.GetString("AppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to something went very wrong!.
        /// </summary>
        public static string StandardError {
            get {
                return ResourceManager.GetString("StandardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is incorrect. Please try again..
        /// </summary>
        public static string UserLoginError {
            get {
                return ResourceManager.GetString("UserLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found with these details..
        /// </summary>
        public static string UserLoginForgotDetailsError {
            get {
                return ResourceManager.GetString("UserLoginForgotDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Admin User is a standard Admin User permission who can do any admin based activities, such as add Use, change user permissions.
        /// </summary>
        public static string UserRoleAdmin {
            get {
                return ResourceManager.GetString("UserRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Master Admin role is for any user who has been given highest permission. Its like God User Permission.
        /// </summary>
        public static string UserRoleMaster {
            get {
                return ResourceManager.GetString("UserRoleMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User role is a standard User of this sytem the role is given to any user who is just a standard User.
        /// </summary>
        public static string UserRoleStandard {
            get {
                return ResourceManager.GetString("UserRoleStandard", resourceCulture);
            }
        }
    }
}
